/**
 * DESIGN.md generator — agent-readable, Stitch-compatible design system file.
 *
 * Takes raw HTML/CSS and extracts a structured markdown document that AI
 * coding agents (Claude Code, Cursor, Stitch, etc.) can read to understand
 * and apply the design system to any project.
 */

export interface DesignMdOutput {
  markdown: string;
  filename: string;
}

/**
 * Extract hex colors from a string of HTML/CSS.
 */
function extractColors(html: string): string[] {
  const hexColors = new Set<string>();
  // Match hex colors: #rgb, #rrggbb, #rrggbbaa
  const hexRegex = /#(?:[0-9a-fA-F]{3,4}){1,2}\b/g;
  let match;
  while ((match = hexRegex.exec(html)) !== null) {
    hexColors.add(match[0].toLowerCase());
  }
  // Match rgb/rgba
  const rgbRegex = /rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/g;
  while ((match = rgbRegex.exec(html)) !== null) {
    const r = parseInt(match[1]);
    const g = parseInt(match[2]);
    const b = parseInt(match[3]);
    const hex = `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`;
    hexColors.add(hex);
  }
  return [...hexColors].sort();
}

/**
 * Extract font families from Tailwind classes and inline styles.
 */
function extractFonts(html: string): string[] {
  const fonts = new Set<string>();
  // font-family in inline styles
  const ffRegex = /font-family:\s*([^;"}]+)/gi;
  let match;
  while ((match = ffRegex.exec(html)) !== null) {
    fonts.add(match[1].trim());
  }
  // Common Tailwind font patterns
  const twFontRegex = /font-(sans|serif|mono|claude-sans|claude-serif|claude-mono)/g;
  const fontMap: Record<string, string> = {
    sans: 'system-ui, -apple-system, sans-serif',
    serif: 'Georgia, serif',
    mono: 'ui-monospace, monospace',
  };
  while ((match = twFontRegex.exec(html)) !== null) {
    const mapped = fontMap[match[1]];
    if (mapped) fonts.add(mapped);
  }
  // Plus Jakarta Sans / Newsreader references
  if (html.includes('Plus Jakarta Sans')) fonts.add('Plus Jakarta Sans, system-ui, sans-serif');
  if (html.includes('Newsreader')) fonts.add('Newsreader, Lora, Georgia, serif');
  if (html.includes('JetBrains Mono')) fonts.add('JetBrains Mono, ui-monospace, monospace');
  return [...fonts];
}

/**
 * Extract Tailwind spacing patterns.
 */
function extractSpacing(html: string): string[] {
  const spacing = new Set<string>();
  const spacingRegex = /(?:p|m|gap|space|px|py|pt|pb|pl|pr|mx|my|mt|mb|ml|mr)-(\d+(?:\.\d+)?)/g;
  let match;
  while ((match = spacingRegex.exec(html)) !== null) {
    const val = parseFloat(match[1]);
    // Tailwind spacing: 1 unit = 0.25rem = 4px
    const px = val * 4;
    spacing.add(`${px}px (${val}rem)`);
  }
  return [...spacing].sort((a, b) => parseFloat(a) - parseFloat(b));
}

/**
 * Extract border radius patterns.
 */
function extractRadii(html: string): string[] {
  const radii = new Set<string>();
  const radiusRegex = /rounded(?:-(\w+))?/g;
  let match;
  const radiusMap: Record<string, string> = {
    sm: '4px',
    md: '6px',
    lg: '8px',
    xl: '12px',
    '2xl': '16px',
    '3xl': '24px',
    full: '9999px',
  };
  while ((match = radiusRegex.exec(html)) !== null) {
    const key = match[1] || 'md';
    radii.add(radiusMap[key] || key);
  }
  return [...radii];
}

/**
 * Extract common background and text color Tailwind classes.
 */
function extractTailwindColors(html: string): Array<{ name: string; class: string }> {
  const colors: Array<{ name: string; class: string }> = [];
  const seen = new Set<string>();

  const bgRegex = /bg-([a-z]+-\d+(?:\/\d+)?)/g;
  let match;
  while ((match = bgRegex.exec(html)) !== null) {
    if (!seen.has(match[0])) {
      seen.add(match[0]);
      colors.push({ name: `background`, class: match[0] });
    }
  }

  const textRegex = /text-([a-z]+-\d+(?:\/\d+)?)/g;
  while ((match = textRegex.exec(html)) !== null) {
    if (!seen.has(match[0])) {
      seen.add(match[0]);
      colors.push({ name: `text`, class: match[0] });
    }
  }

  return colors;
}

/**
 * Generate a DESIGN.md from raw HTML source.
 */
export function generateDesignMd(sourceHtml: string, systemName: string = 'Design System'): DesignMdOutput {
  const colors = extractColors(sourceHtml);
  const fonts = extractFonts(sourceHtml);
  const spacing = extractSpacing(sourceHtml);
  const radii = extractRadii(sourceHtml);
  const twColors = extractTailwindColors(sourceHtml);

  const lines: string[] = [];

  lines.push(`# ${systemName}`);
  lines.push('');
  lines.push('> Agent-readable design system — paste or import this file into any AI coding tool');
  lines.push('> to ensure consistent visual design across your project.');
  lines.push('');
  lines.push(`*Generated by Gia-co-Design on ${new Date().toISOString().split('T')[0]}*`);
  lines.push('');

  // Colors
  lines.push('## Colors');
  lines.push('');
  if (colors.length > 0) {
    lines.push('### Hex Palette');
    lines.push('');
    lines.push('| Color | Hex |');
    lines.push('|-------|-----|');
    for (const c of colors.slice(0, 20)) {
      lines.push(`| ![${c}](https://via.placeholder.com/16/${c.slice(1)}/${c.slice(1)}) | \`${c}\` |`);
    }
    lines.push('');
  }
  if (twColors.length > 0) {
    lines.push('### Tailwind Classes');
    lines.push('');
    for (const tc of twColors.slice(0, 15)) {
      lines.push(`- \`${tc.class}\` — ${tc.name}`);
    }
    lines.push('');
  }

  // Typography
  lines.push('## Typography');
  lines.push('');
  if (fonts.length > 0) {
    lines.push('| Role | Font Family |');
    lines.push('|------|-------------|');
    const roles = ['Body', 'Heading', 'Monospace'];
    fonts.forEach((f, i) => {
      lines.push(`| ${roles[i % roles.length]} | \`${f}\` |`);
    });
    lines.push('');
  }
  lines.push('### Font Sizes');
  lines.push('');
  lines.push('| Token | Size |');
  lines.push('|-------|------|');
  lines.push('| xs | 12px |');
  lines.push('| sm | 14px |');
  lines.push('| base | 16px |');
  lines.push('| lg | 18px |');
  lines.push('| xl | 20px |');
  lines.push('| 2xl | 24px |');
  lines.push('| 3xl | 30px |');
  lines.push('');

  // Spacing
  lines.push('## Spacing');
  lines.push('');
  if (spacing.length > 0) {
    lines.push('| Token | Value |');
    lines.push('|-------|-------|');
    for (const s of spacing.slice(0, 15)) {
      lines.push(`| space | ${s} |`);
    }
    lines.push('');
  }

  // Border Radius
  lines.push('## Border Radius');
  lines.push('');
  if (radii.length > 0) {
    lines.push('| Token | Value |');
    lines.push('|-------|-------|');
    for (const r of radii) {
      lines.push(`| radius | ${r} |`);
    }
    lines.push('');
  }

  // Shadows
  lines.push('## Shadows');
  lines.push('');
  lines.push('- `shadow-sm` — subtle elevation');
  lines.push('- `shadow-md` — card elevation');
  lines.push('- `shadow-lg` — modal/dropdown elevation');
  lines.push('- `shadow-xl` — prominent overlay');
  lines.push('');

  // Component Patterns
  lines.push('## Component Patterns');
  lines.push('');
  lines.push('### Buttons');
  lines.push('- Primary: terracotta background (#d97757), white text, rounded-lg, hover darkens');
  lines.push('- Secondary: transparent/surface background, border, text inherits');
  lines.push('- Sizes: sm (px-2.5 py-1.5), md (px-3 py-1.5), lg (px-4 py-2)');
  lines.push('');
  lines.push('### Cards');
  lines.push('- Rounded-xl, border, shadow-lg');
  lines.push('- Light: bg-[#f4f0e8] border-[#e2ddd3]');
  lines.push('- Dark: bg-[#22201d] border-[#38342e]');
  lines.push('');
  lines.push('### Inputs');
  lines.push('- Rounded-lg, border, text-sm');
  lines.push('- Focus ring: ring-2 ring-[#d97757]');
  lines.push('');

  // Layout
  lines.push('## Layout');
  lines.push('');
  lines.push('- Max content width: none (full-bleed)');
  lines.push('- Grid: Tailwind grid/flex utilities');
  lines.push('- Breakpoints: sm (640px), md (768px), lg (1024px), xl (1280px)');
  lines.push('');

  // Usage
  lines.push('## Usage');
  lines.push('');
  lines.push('```');
  lines.push('# How to use this file:');
  lines.push('');
  lines.push('# In Claude Code / Cursor / Windsurf:');
  lines.push('# Paste this file as context, or point the AI to it.');
  lines.push('# The AI will use these tokens and patterns in all generated code.');
  lines.push('');
  lines.push('# In Google Stitch:');
  lines.push('# Import via DESIGN.md or paste the contents as a reference.');
  lines.push('');
  lines.push('# In any project:');
  lines.push('# Copy the tokens into your CSS variables or Tailwind config.');
  lines.push('```');

  const markdown = lines.join('\n');
  const filename = `${systemName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-design-system.md`;

  return { markdown, filename };
}

/**
 * Download a DESIGN.md file.
 */
export function downloadDesignMd(output: DesignMdOutput): void {
  const blob = new Blob([output.markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = output.filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
